version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/QueryStringGenerator"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/QueryStringGenerator.App"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/QueryStringGenerator.Tests"
    schedule:
      interval: "daily"
